/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hxb_xb_testandroidfunction_test_jni_HelloJni */

#ifndef _Included_hxb_xb_testandroidfunction_test_jni_HelloJni
#define _Included_hxb_xb_testandroidfunction_test_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hxb_xb_testandroidfunction_test_jni_HelloJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hxb_xb_1testandroidfunction_test_1jni_HelloJni_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     hxb_xb_testandroidfunction_test_jni_HelloJni
 * Method:    unimplementedStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hxb_xb_1testandroidfunction_test_1jni_HelloJni_unimplementedStringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
